name: Thai
title: Thai Vu
description: >
  A homo sapiens

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

defaults:
  -
    scope:
      path:            "_posts/*.md"
    values:
      sitemap:         true
